[ -f ~/.dotfilesrc ] \
  && source ~/.dotfilesrc \
  || echo "\e[0;31m ✖ ~/.dotfilesrc file which exports \$DOTFILES_DIR path is missing\e[0m\n"

plugins=(fasd fzf)

source $DOTFILES_DIR/shell/exports
source $DOTFILES_DIR/shell/aliases
source $DOTFILES_DIR/shell/functions
source $DOTFILES_DIR/shell/config
source $ZSH/oh-my-zsh.sh

autoload -Uz compinit; compinit

# npm tab completion
source <(npm completion)

# Bash completions
if exists brew; then
  [ -f $(brew --prefix)/etc/bash_completion ] \
    && source $(brew --prefix)/etc/bash_completion
fi

# Source local extra (private) settings specific to the machine
[ -f ~/.zsh.local ] && source ~/.zsh.local

# scmpuff for easier Git commits
eval "$(scmpuff init -s --aliases=false)"
