[ -f ~/.dotfilesrc ] \
  && source ~/.dotfilesrc \
  || echo "\e[0;31m ✖ ~/.dotfilesrc file which exports \$DOTFILES_DIR path is missing\e[0m\n"

source $DOTFILES_DIR/shell/exports
source $DOTFILES_DIR/shell/aliases
source $DOTFILES_DIR/shell/functions
source $DOTFILES_DIR/shell/config
source $ZSH/oh-my-zsh.sh

autoload -Uz compinit; compinit

# npm tab completion
# . <(npm completion)

# Bash completions
if exists brew; then
  [ -f $(brew --prefix)/etc/bash_completion ] \
    && source $(brew --prefix)/etc/bash_completion
fi

if exists brew; then
  # Initialise fasd
  eval "$(fasd --init auto)"

  # Initialise fzf
  source $DOTFILES_DIR/shell/fzf
fi

# Source local extra (private) settings specific to the machine
[ -f ~/.zsh.local ] && source ~/.zsh.local

# scmpuff for easier Git commits
eval "$(scmpuff init -s --aliases=false)"
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
